app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('api/v1/', include('authentication.urls')),

    path('', views.home, name='home'),
    path('', include('brands.urls')),
    path('', include('categories.urls')),
    path('', include('suppliers.urls')),
    path('', include('inflows.urls')),
    path('', include('outflows.urls')),
    path('', include('products.urls')),
]

products/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('products/list/', views.ProductListView.as_view(), name='product_list'),
    path('products/create/', views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/detail/', views.ProductDetailView.as_view(), name='product_detail'),
    path('products/<int:pk>/update/', views.ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', views.ProductDeleteView.as_view(), name='product_delete'),

    path('api/v1/products/', views.ProductCreateListAPIView.as_view(), name='product-create-list-api-view'),
    path('api/v1/products/<int:pk>/', views.ProductRetrieveUpdateDestroyAPIView.as_view(), name='product-detail-api-view'),
]

outflows/models.py
from django.db import models
from products.models import Product


class Outflow(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='outflows')
    quantity = models.IntegerField()
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return str(self.product)

products/models.py
from django.db import models
from brands.models import Brand
from categories.models import Category


class Product(models.Model):
    title = models.CharField(max_length=500)
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT, related_name='products')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='products')
    description = models.TextField(blank=True, null=True)
    serie_number = models.CharField(max_length=200, null=True, blank=True)
    cost_price = models.DecimalField(max_digits=20, decimal_places=2)
    selling_price = models.DecimalField(max_digits=20, decimal_places=2)
    quantity = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

products/forms.py
from django import forms
from . import models


class ProductForm(forms.ModelForm):

    class Meta:
        model = models.Product
        fields = ['title', 'category', 'brand', 'description', 'serie_number', 'cost_price', 'selling_price',]
        labels = {
            'title': 'Título',
            'category': 'Categoria',
            'brand': 'Marca',
            'description': 'Descrição',
            'serie_number': 'Número de Série',
            'cost_price': 'Preço de Custo',
            'selling_price': 'Preço de Venda',
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'brand': forms.Select(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'serie_number': forms.TextInput(attrs={'class': 'form-control'}),
            'cost_price': forms.NumberInput(attrs={'class': 'form-control'}),
            'selling_price': forms.NumberInput(attrs={'class': 'form-control'}),

        }

products/views.py
from rest_framework import generics
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from app import metrics
from categories.models import Category
from brands.models import Brand
from . import models, forms, serializers


class ProductListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = models.Product
    template_name = 'product_list.html'
    context_object_name = 'products'
    paginate_by = 10
    permission_required = 'products.view_product'

    def get_queryset(self):
        queryset = super().get_queryset()
        title = self.request.GET.get('title')
        serie_number = self.request.GET.get('serie_number')
        Product = self.request.GET.get('Product')
        brand = self.request.GET.get('brand')

        if title:
            queryset = queryset.filter(title__icontains=title)

        if serie_number:
            queryset = queryset.filter(serie_number__icontains=serie_number)

        if Product:
            queryset = queryset.filter(Product__id=Product)

        if brand:
            queryset = queryset.filter(brand__id=brand)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product_metrics'] = metrics.get_product_metrics()
        context['categories'] = Category.objects.all()
        context['brands'] = Brand.objects.all()
        return context


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.Product
    template_name = 'product_create.html'
    form_class = forms.ProductForm
    success_url = reverse_lazy('product_list')
    permission_required = 'products.add_product'


class ProductDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = models.Product
    template_name = 'product_detail.html'
    permission_required = 'products.view_product'


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = models.Product
    template_name = 'product_update.html'
    form_class = forms.ProductForm
    success_url = reverse_lazy('product_list')
    permission_required = 'products.change_product'


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = models.Product
    template_name = 'product_delete.html'
    success_url = reverse_lazy('product_list')
    permission_required = 'products.delete_product'


class ProductCreateListAPIView(generics.ListCreateAPIView):
    queryset = models.Product.objects.all()
    serializer_class = serializers.ProductSerializer


class ProductRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.Product.objects.all()
    serializer_class = serializers.ProductSerializer

products/templates/product_create.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Cadastrar Produto</h3>

    <div class="card">
        <div class="card-body">
            <form method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar Produto</button>
            </form>
        </div>
    </div>
    <a href="{% url 'product_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar para a Lista de Produtos</a>
</div>

{% endblock %}

products/templates/product_delete.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-4">
        <h3 class="display-6">Deletar Produto</h3>

        <div class="card">
            <div class="card-body">
                <p class="card-text">Tem certeza que deseja deletar o produto <strong>{{ object.title }}</strong>?</p>

                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger mt-3">Deletar</button>
                </form>
                
            </div>
            
        </div>
        <a href="{% url 'product_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar para a Lista de Produtos</a>
    </div>



{% endblock %}

products/templates/product_detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-4">
        <h3 class="display-6">Detalhes da Produto</h3>

        <div class="card">
            <div class="card-body">
                <h3 class="card-title">{{ object.title }}</h3>
                <p class="card-text">Categoria: {{ object.category }}</p>
                <p class="card-text">Marca: {{ object.brand }}</p>
                <p class="card-text">Descrição: {{ object.description }}</p>
                <p class="card-text">Número de Série: <strong>{{ object.serie_number }}</strong></p>
                <p class="card-text">Preço de Custo: <strong>R$ {{ object.cost_price }}</strong></p>
                <p class="card-text">Preço de Venda: <strong>R$ {{ object.selling_price }}</strong></p>
                <p class="card-text">Quantidade em Estoque: <strong>{{ object.quantity }}</strong></p>
            </div>
        </div>
        <a href="{% url 'product_list' %}" class="btn btn-secondary mt-3">Voltar para a Lista de Produtos</a>
    </div>

{% endblock %}

products/templates/product_list.html
{% extends 'base.html' %}

{% block title %}
SGE - Produtos
{% endblock %}

{% block content %}

  {% if perms.products.add_product and perms.outflows.add_outflow %}
    {% include 'components/_product_metrics.html' %}
  {% endif %}

<div class="mb-4"></div>

<div class="row mb-3">
    <div class="col-md-6">
        <form method="get" action="{% url 'product_list' %}">
            <div class="input-group">
                <input type="text" class="form-control" name="title" placeholder="Título" value="{{ request.GET.title }}">
                <input type="text" class="form-control" name="serie_number" placeholder="Número de Série" value="{{ request.GET.serie_number }}">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-search"></i>
                </button>
                
            </div>
        </form>
    </div>

    {% if perms.products.add_product %}
      <div class="col-md-6">
        <a href="{% url 'product_create' %}" class="btn btn-success float-end">
            <i class="bi bi-plus"></i> Novo Produto
        </a>
      </div>
    {% endif %} 
</div>
<div class="row mb-3">
    <div class="col-md-6">
        <form method="get" action="{% url 'product_list' %}">
            <div class="input-group">
                <select class="form-select" name="category">
                    <option value="" {% if not request.GET.category %} selected {% endif %}>Todas as Categorias</option>
                    {% for category in categories %}
                        <option value="{{ category.id }}" {% if request.GET.category == category.id %} selected {% endif %}>{{ category.name }}</option>
                    {% endfor %}
                </select>

                <select class="form-select" name="brand">
                    <option value="" {% if not request.GET.brand %} selected {% endif %}>Todas as Marcas</option>
                    {% for brand in brands %}
                        <option value="{{ brand.id }}" {% if request.GET.brand == brand.id %} selected {% endif %}>{{ brand.name }}</option>
                    {% endfor %}
                </select>

                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-filter"></i> Filtrar
                </button>
            </div>
            

        </form>
    </div>

</div>



<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Título</th>
                <th>Categoria</th>
                <th>Marca</th>
                <th>Preço de Custo</th>
                <th>Preço de Venda</th>
                <th>Número de Série</th>
                <th>Quantidade</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ product.id }}</td>
                    <td>{{ product.title }}</td>
                    <td>{{ product.category }}</td>
                    <td>{{ product.brand }}</td>
                    <td>{{ product.cost_price }}</td>
                    <td>{{ product.selling_price }}</td>
                    <td>{{ product.serie_number }}</td>
                    <td>{{ product.quantity }}</td>
                    <td>

                      {% if perms.products.view_product %}
                        <a href="{% url 'product_detail' product.id %}" class="btn btn-info btn-sm">
                            <i class="bi bi-eye"></i>
                        </a>
                      {% endif %}

                      {% if perms.products.change_product %}
                        <a href="{% url 'product_update' product.id %}" class="btn btn-warning btn-sm">
                            <i class="bi bi-pencil"></i>
                        </a>
                      {% endif %}

                      {% if perms.products.delete_product %}
                        <a href="{% url 'product_delete' product.id %}" class="btn btn-danger btn-sm">
                            <i class="bi bi-trash3"></i>
                        </a>
                      {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% include 'components/_pagination.html' %}

{% endblock %}

products/templates/product_update.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-4">
        <h3 class="display-6">Editar Produto</h3>

        <div class="card">
            <div class="card-body">
                <form method="post" class="form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Salvar Produto</button>
                </form>
            </div>
        </div>
        <a href="{% url 'product_list' %}" class="btn btn-secondary mt-3">Cancelar e Voltar para a Lista de Produtos</a>
    </div>

{% endblock %}